//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plato_Reserva
    {
        public int ID_Plato_Admin { get; set; }
        public string UsuarioModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int Reserva_Admin_ID_Reserva_Admin { get; set; }
        public int Platos_Inventario_ID_Plato { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual Platos_Inventario Platos_Inventario { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
